#!/usr/bin/env python3
"""Pull per-profile pageview totals from Umami into _data/views.yaml.

The site already sends pageviews to Umami (see _includes/analytics.html).
This script reads them back out at build time so the counts can be rendered
as static HTML — no extra third-party request from the visitor's browser,
and nothing new collected about them.

Configuration comes from the environment:

  UMAMI_API_KEY      required; create one in Umami Cloud under Settings > API
  UMAMI_WEBSITE_ID   optional; defaults to `analytics.umami_website_id` in
                     _config.yaml, which is the same id the tracking script
                     already uses
  UMAMI_API_URL      optional; defaults to Umami Cloud. For a self-hosted
                     instance use https://your-host/api
  UMAMI_START_DATE   optional; YYYY-MM-DD, defaults to 2020-01-01. Counts are
                     cumulative from this date forward.

So in practice UMAMI_API_KEY is the only thing that needs configuring, as a
repository secret. Without it the script is a no-op and exits 0, so builds on
forks and pull requests (which have no access to secrets) keep working and
simply render no counts.

Only member profile paths are written out, which keeps the data file small
and its diffs readable. To count other page types too, widen
`wanted_paths()`.
"""

import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import date, datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MEMBERS_DIR = REPO / "_members"
OUTPUT = REPO / "_data" / "views.yaml"
CONFIG = REPO / "_config.yaml"

DEFAULT_API_URL = "https://api.umami.is/v1"
DEFAULT_START_DATE = "2020-01-01"
MEMBER_URL_PREFIX = "/members/"
TIMEOUT = 30


def website_id_from_config():
    """Read analytics.umami_website_id out of _config.yaml.

    A deliberately small scan rather than a YAML parse, so this script keeps
    to the standard library and needs no install step in CI.
    """
    try:
        text = CONFIG.read_text()
    except OSError:
        return ""
    match = re.search(r"^\s+umami_website_id:\s*(\S+)\s*$", text, re.MULTILINE)
    return match.group(1).strip("\"'") if match else ""


def wanted_paths():
    """Map tracked URL paths to the `page.url` the site renders them at.

    Jekyll's default collection permalink puts member pages at
    /members/<slug>.html, which is the key the Liquid include looks up. Both
    that path and its extension-less form are accepted, so counts survive a
    permalink change or a redirect that drops the .html.

    Collection files whose names start with "_" or "." never become pages
    (Jekyll skips them), so they are skipped here too.
    """
    paths = {}
    for path in sorted(MEMBERS_DIR.glob("*.md")):
        if path.name.startswith(("_", ".")):
            continue
        canonical = f"{MEMBER_URL_PREFIX}{path.stem}.html"
        paths[normalize(canonical)] = canonical
        paths[normalize(f"{MEMBER_URL_PREFIX}{path.stem}")] = canonical
    return paths


def normalize(url):
    """Reduce a tracked URL to a bare, comparable path.

    Drops the query and fragment, collapses repeated slashes, and trims a
    trailing slash so /members/foo/ and /members/foo compare equal.
    """
    if not isinstance(url, str) or not url:
        return None
    path = url.split("?", 1)[0].split("#", 1)[0]
    if not path.startswith("/"):
        path = "/" + path
    path = re.sub(r"/{2,}", "/", path)
    if len(path) > 1:
        path = path.rstrip("/")
    return path


def to_millis(day):
    return int(
        datetime(day.year, day.month, day.day, tzinfo=timezone.utc).timestamp() * 1000
    )


def fetch_metrics(api_url, website_id, api_key, start_at, end_at):
    query = urllib.parse.urlencode(
        {
            "startAt": start_at,
            "endAt": end_at,
            "type": "url",
            "limit": 1000,
        }
    )
    request = urllib.request.Request(
        f"{api_url.rstrip('/')}/websites/{website_id}/metrics?{query}",
        headers={
            "x-umami-api-key": api_key,
            "Accept": "application/json",
            "User-Agent": "draco-website-view-counter",
        },
    )
    with urllib.request.urlopen(request, timeout=TIMEOUT) as response:
        return json.load(response)


def write_yaml(counts, start_date, total):
    lines = [
        "# Auto-generated by _analytics/fetch_views.py — do not edit by hand.",
        "# Cumulative profile pageviews, read back out of Umami at build time.",
        f"updated: {date.today().isoformat()}",
        f"range_start: {start_date}",
        f"total: {total}",
        "pages:",
    ]
    if counts:
        for path in sorted(counts):
            lines.append(f'  "{path}": {counts[path]}')
    else:
        lines[-1] = "pages: {}"
    OUTPUT.write_text("\n".join(lines) + "\n")


def main():
    api_key = os.environ.get("UMAMI_API_KEY", "").strip()
    website_id = os.environ.get("UMAMI_WEBSITE_ID", "").strip() or website_id_from_config()

    if not api_key:
        print(f"UMAMI_API_KEY not set — leaving {OUTPUT.relative_to(REPO)} untouched.")
        return 0

    if not website_id:
        print(
            "No website id: set UMAMI_WEBSITE_ID or analytics.umami_website_id "
            "in _config.yaml.",
            file=sys.stderr,
        )
        return 1

    api_url = os.environ.get("UMAMI_API_URL", "").strip() or DEFAULT_API_URL
    start_date = os.environ.get("UMAMI_START_DATE", "").strip() or DEFAULT_START_DATE

    try:
        start_day = date.fromisoformat(start_date)
    except ValueError:
        print(f"UMAMI_START_DATE must be YYYY-MM-DD, got {start_date!r}", file=sys.stderr)
        return 1

    try:
        metrics = fetch_metrics(
            api_url,
            website_id,
            api_key,
            to_millis(start_day),
            to_millis(date.today()) + 86_400_000,
        )
    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError) as error:
        print(f"Could not reach Umami ({error}) — leaving views data as-is.", file=sys.stderr)
        return 1
    except json.JSONDecodeError as error:
        print(f"Umami returned unparseable JSON ({error}).", file=sys.stderr)
        return 1

    if not isinstance(metrics, list):
        print(f"Unexpected Umami response shape: {type(metrics).__name__}", file=sys.stderr)
        return 1

    wanted = wanted_paths()
    counts = {}
    for row in metrics:
        if not isinstance(row, dict):
            continue
        canonical = wanted.get(normalize(row.get("x")))
        if not canonical:
            continue
        try:
            views = int(row.get("y") or 0)
        except (TypeError, ValueError):
            continue
        if views > 0:
            counts[canonical] = counts.get(canonical, 0) + views

    write_yaml(counts, start_date, sum(counts.values()))
    print(
        f"Wrote {len(counts)} profile view counts "
        f"({sum(counts.values())} views total) to {OUTPUT.relative_to(REPO)}."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
